let itemVars = {
    weapons:{
        rod:{
            weapon:true,
            name:"rod",
            damage:2,
            stunTime:3,
            weight:2,
            type:{
                blunt:true,
                long:true
            },
            value:3
        },
        club:{
            weapon:true,
            name:"club",
            damage:4,
            stunTime:3,
            weight:2,
            type:{
                blunt:true
            },
            jab:{
                damage:2,
                stunTime:2,
                weight:2,
                type:{
                    blunt:true
                }
            },
            value:2
        },
        mace:{
            weapon:true,
            name:"mace",
            damage:5,
            stunTime:3,
            weight:2,
            type:{
                blunt:true
            },
            jab:{
                damage:2,
                stunTime:2,
                weight:2,
                type:{
                    blunt:true
                }
            },
            value:4
        },
        hammer:{
            weapon:true,
            name:"hammer",
            damage:8,
            stunTime:5,
            weight:3,
            type:{
                blunt:true
            },
            jab:{
                damage:2,
                stunTime:4,
                weight:2,
                type:{
                    blunt:true
                }
            },
            value:5
        },
        maul:{
            weapon:true,
            name:"maul",
            damage:12,
            stunTime:7,
            weight:4,
            type:{
                blunt:true
            },
            jab:{
                damage:2,
                stunTime:5,
                weight:3,
                type:{
                    blunt:true
                }
            },
            value:7
        },
        rapier:{
            weapon:true,
            name:"rapier",
            damage:2,
            stunTime:2,
            weight:1,
            type:{
                sword:true,
            },
            jab:{
                damage:8,
                stunTime:2,
                weight:2,
                type:{
                    sword:true,
                },
            },
            value:7
        },
        shortsword:{
            weapon:true,
            name:"shortsword",
            damage:4,
            stunTime:2,
            weight:2,
            type:{
                sword:true,
                edged:true
            },
            value:4
        },
        longsword:{
            weapon:true,
            name:"longsword",
            damage:8,
            stunTime:3,
            weight:3,
            type:{
                sword:true,
                edged:true
            },
            value:7
        },
        greatsword:{
            weapon:true,
            name:"greatsword",
            damage:12,
            stunTime:4,
            weight:4,
            type:{
                sword:true,
                edged:true
            },
            value:10
        },
        handaxe:{
            weapon:true,
            name:"handaxe",
            damage:1,
            stunTime:2,
            weight:2,
            type:{
                edged:true
            },
            swing:{
                damage:6,
                stunTime:4,
                weight:2,
                type:{
                    edged:true
                }
            },
            value:4
        },
        greataxe:{
            weapon:true,
            name:"greataxe",
            damage:2,
            stunTime:3,
            weight:3,
            type:{
                edged:true
            },
            swing:{
                damage:15,
                stunTime:6,
                weight:4,
                type:{
                    edged:true
                }
            },
            value:9
        },
        halberd:{
            weapon:true,
            name:"halberd",
            damage:10,
            stunTime:3,
            weight:3,
            type:{
                edged:true,
                long:true
            },
            swing:{
                damage:15,
                stunTime:4,
                weight:5,
                type:{
                    edged:true,
                    long:true
                }
            },
            value:8
        },
    },
    fuel:{
        oilFlask:{
            usable:true,
            name: "oil flask",
            fuel:true,
            light:2,
            uses:3,
            value:5
        },
        kindling:{
            usable:true,
            name: "kindling",
            fuel:true,
            light:1,
            value:1,
            color:'woodBrown'
        }
    },
    drops:{
        direRatPelt:{
            name:"dire rat pelt",
            value:1,
            color:'brown'
        },
        wolfPelt:{
            name:"wolf pelt",
            value:2,
            color:'brown'
        },
        direWolfPelt:{
            name:"dire wolf pelt",
            value:4,
            color:'gray'
        },
        kingRatSkull:{
            name:"king rat's skull",
            value:15,
            color:'red'
        }
    },
    treasure:{
        thimble:{
            name:"thimble",
            value:1
        },
        ring:{
            name:"ring",
            value:4
        },
        cup:{
            name:"cup",
            value:6
        },
        plate:{
            name:"plate",
            value:8
        },
        vase:{
            name:"vase",
            value:10
        },
        pendant:{
            name:"pendant",
            value:6
        },
        statuette:{
            name:"statuette",
            value:12
        },
        crown:{
            name:"crown",
            value:20
        },
        tiara:{
            name:"tiara",
            value:12
        },
        coinPouch:{
            name:"coin pouch",
            value:10
        }
    },
    weaponMaterials:{
        wood:{
            name:'wooden',
            flimsy:5,
            stunTime: -2,
            weight:-1,
            damage:-4,
            value:.25,
            color:'woodBrown',

            usable:true,
            fuel:true,
            light:1,

        },
        bone:{
            name:'bone',
            flimsy:8,
            stunTime:-2,
            weight:-1,
            damage: -3,
            value:.15,
            color:'bone'
        },
        limestone:{
            name:'limestone',
            flimsy:6,
            weight:2,
            stunTime:3,
            blunt:{
                damage:4
            },
            edged:{
                damage:2
            },
            value:.2,
            color:'silver'
        },
        flint:{
            name:'flint',
            flimsy:4,
            value:.3,
            color:'darkGray'
        },
        obsidian:{
            name:'obsidian',
            flimsy:6,
            edged:{
                damage:2
            },
            value:.5
        },
        lead:{
            name:'lead',
            flimsy:3,
            weight:1,
            stunTime:2,
            blunt:{
                damage:5
            },
            edged:{
                damage:3
            },
            value:2,
            color:'darkgray'
        },
        rubber:{
            name:'rubber',
            blunt:{
                damage:-5,
                stunTime:2
            },
            edged:{
                damage:-8
            },
            value:.5
        },
        glass:{
            name:'glass',
            flimsy:40,
            value:3,
            edged:{
                damage:6
            },
            color:'clearBlue'
        },
        copper:{
            name:'copper',
            flimsy:3,
            value:2,
            color:'redBrown'
        },
        bronze:{
            name:'bronze',
            flimsy:2,
            edged:{
                damage:1
            },
            value:3,
            color:'brown'
        },
        iron:{
            name:'iron',
            flimsy:1,
            edged:{
                damage:1
            },
            value:2.5,
            color:'gray'
        },
        steel:{
            name:'steel',
            edged:{
                damage:2
            },
            value:4.5,
            value:2,
            color:'lightGray'
        },
        ironwood:{
            name:'ironwood',
            stunTime:2,
            blunt:{
                damage:2
            },
            edged:{
                damage:-1
            },
            value:6,
            value:3,
            color:'redBrown'
        },
        crystal:{
            name:'crystal',
            flimsy:20,
            value:8,
            edged:{
                damage:8
            },
            color:'darkPurple'
        },
        lightsteel:{
            name:'lightsteel',
            weight:-1,
            stunTime:-2,
            blunt:{
                damage:-2
            },
            edged:{
                damage:2
            },
            value:8,
            color:'silver'

        },
        silver:{
            name:'silver',
            flimsy:5,
            edged:{
                damage:-1
            },
            value:10,
            color:'silver'
        },
        gold:{
            name:'gold',
            weight:1,
            stunTime:2,
            flimsy:8,
            edged:{
                damage:-2
            },
            blunt:{
                damage:2
            },
            value:12,
            color:'gold'
        },
        Adamantine:{
            name:'adamantine',
            weight:-1,
            edged:{
                damage:2
            },
            value:20,
            color:'blue'
        }
    },
    treasureMaterials:{
        paper:{
            name:"paper",
            value:.05,
            color:"bone",

            usable:true,
            fuel:true,
            light:2,
        },
        bone:{
            name:"bone",
            value:0.2,
            color:"bone"
        },
        wood:{
            name:'wooden',
            value:0.3,
            color:"woodBrown",

            usable:true,
            fuel:true,
            light:1,
        },
        stone:{
            name:'stone',
            value:0.4,
            color:"gray"
        },
        
        iron:{
            name:'iron',
            value:.6,
            color:"gray"
        },
        steel:{
            name:'steel',
            value:1,
            color:"lightGray"
        },
        bronze:{
            name:'bronze',
            value:1.2,
            color:"brown"
        },
        lead:{
            name:'lead',
            value:2,
            color:"darkgray"
        },
        copper:{
            name:'copper',
            value:3,
            color:"redBrown"
        },
        nickel:{
            name:'nickel',
            value:3.5,
            color:"lightGray"
        },
        tin:{
            name:'tin',
            value:4,
            color:"lightGray"
        },
        sterling:{
            name:'sterling silver',
            value:5,
            color:'silver'
        },
        silver:{
            name:'silver',
            value:8,
            color:"silver"
        },
        gold:{
            name:'gold',
            value:10,
            color:"gold"
        },
        platinum:{
            name:'platinum',
            value:20,
            color:"silver"
        }
    },
    weaponModifiers:{
        worn:{
            name:'worn',
            flimsy:1,
            edged:{
                damage:-1
            },
            value:.4
        },
        craftTiers:{
            poor:{
                name:'poor',
                flimsy:3,
                variance:{
                    positive:0,
                    negative:50
                },
                value:.4
            },
            rustic:{
                name:'rustic',
                flimsy:1,
                variance:{
                    positive:20,
                    negative:50
                },
                value:.7
            },
            artisan:{
                name:'artisan',
                variance:{
                    positive:30,
                    negative:30
                },
                value:1.2
            },
            masterwork:{
                name:'masterwork',
                variance:{
                    positive:50,
                    negative:10
                },
                value:5
            }
        }
    },
    treasureModifiers:{
        decrepit:{
            name:'decrepit',
            value:.4
        },
        distressed:{
            name:'distressed',
            value:.6
        },
        pristine:{
            name:'pristine',
            value:1.5
        } 
    },
    food:{
        morsel:{
            name:'morsel',
            usable: true,
            food:1
        }
    }
}