let itemVars = {
    weapons:{
        rod:{
            weapon:true,
            name:"rod",
            damage:2,
            stunTime:3,
            weight:1,
            type:{
                blunt:true,
                long:true
            },
            value:3
        },
        club:{
            weapon:true,
            name:"club",
            damage:4,
            stunTime:3,
            weight:1,
            type:{
                blunt:true
            },
            jab:{
                damage:2,
                stunTime:2,
                weight:1,
                type:{
                    blunt:true
                }
            },
            value:2
        },
        mace:{
            weapon:true,
            name:"mace",
            damage:5,
            stunTime:3,
            weight:1,
            type:{
                blunt:true
            },
            jab:{
                damage:2,
                stunTime:2,
                weight:1,
                type:{
                    blunt:true
                }
            },
            value:4
        },
        hammer:{
            weapon:true,
            name:"hammer",
            damage:8,
            stunTime:5,
            weight:2,
            type:{
                blunt:true
            },
            jab:{
                damage:2,
                stunTime:4,
                weight:1,
                type:{
                    blunt:true
                }
            },
            value:5
        },
        maul:{
            weapon:true,
            name:"maul",
            damage:12,
            stunTime:7,
            weight:3,
            type:{
                blunt:true
            },
            jab:{
                damage:2,
                stunTime:5,
                weight:2,
                type:{
                    blunt:true
                }
            },
            value:7
        },
        rapier:{
            weapon:true,
            name:"rapier",
            damage:2,
            stunTime:2,
            weight:1,
            type:{
                sword:true,
            },
            jab:{
                damage:8,
                stunTime:2,
                weight:1,
                type:{
                    sword:true,
                },
            },
            value:7
        },
        shortsword:{
            weapon:true,
            name:"shortsword",
            damage:4,
            stunTime:2,
            weight:1,
            type:{
                sword:true,
                edged:true
            },
            value:4
        },
        longsword:{
            weapon:true,
            name:"longsword",
            damage:8,
            stunTime:3,
            weight:2,
            type:{
                sword:true,
                edged:true
            },
            value:7
        },
        greatsword:{
            weapon:true,
            name:"greatsword",
            damage:12,
            stunTime:4,
            weight:3,
            type:{
                sword:true,
                edged:true
            },
            value:10
        },
        handaxe:{
            weapon:true,
            name:"handaxe",
            damage:1,
            stunTime:2,
            weight:1,
            type:{
                edged:true
            },
            swing:{
                damage:6,
                stunTime:4,
                weight:1,
                type:{
                    edged:true
                }
            },
            value:4
        },
        greataxe:{
            weapon:true,
            name:"greataxe",
            damage:2,
            stunTime:3,
            weight:2,
            type:{
                edged:true
            },
            swing:{
                damage:15,
                stunTime:6,
                weight:3,
                type:{
                    edged:true
                }
            },
            value:9
        },
        halberd:{
            weapon:true,
            name:"halberd",
            damage:10,
            stunTime:3,
            weight:2,
            type:{
                edged:true,
                long:true
            },
            swing:{
                damage:15,
                stunTime:4,
                weight:4,
                type:{
                    edged:true,
                    long:true
                }
            },
            value:8
        },
    },
    fuel:{
        oilFlask:{
            usable:true,
            name: "oil flask",
            fuel:true,
            light:2,
            uses:3,
            value:5
        }
    },
    treasure:{
        thimble:{
            name:"thimble",
            value:1
        },
        ring:{
            name:"ring",
            value:2
        },
        cup:{
            name:"cup",
            value:3
        },
        plate:{
            name:"plate",
            value:5
        },
        vase:{
            name:"vase",
            value:7
        },
        pendant:{
            name:"pendant",
            value:3
        },
        statuette:{
            name:"statuette",
            value:8
        },
        crown:{
            name:"crown",
            value:15
        },
        tiara:{
            name:"tiara",
            value:12
        },
        coinPouch:{
            name:"coin pouch",
            value:10
        }
    },
    weaponMaterials:{
        wood:{
            name:'wooden',
            flimsy:5,
            stunTime: -1,
            edged:{
                damage:-2
            },
            blunt:{
                damage:-1
            },
            value:.25
        },
        bone:{
            name:'bone',
            flimsy:8,
            stunTime:-1,
            edged:{
                damage:-1
            },
            value:.15
        },
        stone:{
            name:'stone',
            flimsy:5,
            weight:2,
            stunTime:3,
            blunt:{
                damage:4
            },
            edged:{
                damage:2
            },
            value:.2
        },
        lead:{
            name:'lead',
            flimsy:3,
            weight:1,
            stunTime:2,
            blunt:{
                damage:5
            },
            edged:{
                damage:3
            },
            value:1
        },
        rubber:{
            name:'rubber',
            blunt:{
                damage:-5,
                stunTime:2
            },
            edged:{
                damage:-8
            },
            value:.5
        },
        glass:{
            name:'glass',
            flimsy:40,
            value:2,
            edged:{
                damage:6
            }
        },
        bronze:{
            name:'bronze',
            flimsy:2,
            value:1.5
        },
        iron:{
            name:'iron',
            flimsy:1,
            value:1.2,
        },
        steel:{
            name:'steel',
            edged:{
                damage:2
            },
            value:2
        },
        ironwood:{
            name:'ironwood',
            stunTime:2,
            blunt:{
                damage:2
            },
            value:3
        },
        crystal:{
            name:'crystal',
            flimsy:20,
            value:6,
            edged:{
                damage:8
            }
        },
        lightsteel:{
            name:'lightsteel',
            weight:-1,
            stunTime:-2,
            blunt:{
                damage:-2
            },
            edged:{
                damage:2
            },
            value:3
        },
        silver:{
            name:'silver',
            flimsy:5,
            edged:{
                damage:-1
            },
            value:5
        },
        gold:{
            name:'gold',
            weight:1,
            stunTime:2,
            flimsy:8,
            edged:{
                damage:-2
            },
            blunt:{
                damage:2
            },
            value:6
        },
        Adamantine:{
            name:'adamantine',
            weight:-1,
            edged:{
                damage:2
            },
            value:10
        }
    },
    treasureMaterials:{
        paper:{
            name:"tattered paper",
            value:.05
        },
        bone:{
            name:"bone",
            value:0.2
        },
        wood:{
            name:'wooden',
            value:0.3
        },
        stone:{
            name:'stone',
            value:0.4
        },
        
        iron:{
            name:'iron',
            value:.6
        },
        steel:{
            name:'steel',
            value:1
        },
        bronze:{
            name:'bronze',
            value:1.2
        },
        lead:{
            name:'lead',
            value:2
        },
        copper:{
            name:'copper',
            value:3
        },
        nickel:{
            name:'nickel',
            value:3.5
        },
        tin:{
            name:'tin',
            value:4
        },
        sterling:{
            name:'sterling silver',
            value:5
        },
        silver:{
            name:'silver',
            value:8
        },
        gold:{
            name:'gold',
            value:10
        },
        platinum:{
            name:'platinum',
            value:20
        }
    },
    weaponModifiers:{
        worn:{
            name:'worn',
            flimsy:1,
            edged:{
                damage:-1
            },
            value:.4
        },
        craftTiers:{
            poor:{
                name:'poor',
                flimsy:3,
                variance:{
                    positive:0,
                    negative:50
                },
                value:.4
            },
            rustic:{
                name:'rustic',
                flimsy:1,
                variance:{
                    positive:20,
                    negative:50
                },
                value:.7
            },
            artisan:{
                name:'artisan',
                variance:{
                    positive:30,
                    negative:30
                },
                value:1.2
            },
            masterwork:{
                name:'masterwork',
                variance:{
                    positive:50,
                    negative:10
                },
                value:5
            }
        }
    }
}