let itemVars = {
    weapons:{
        rod:{
            weapon:true,
            name:"rod",
            damage:2,
            stunTime:3,
            weight:1,
            type:{
                blunt:true,
                long:true
            },
            value:3
        },
        club:{
            weapon:true,
            name:"club",
            damage:4,
            stunTime:3,
            weight:1,
            type:{
                blunt:true
            },
            jab:{
                damage:2,
                stunTime:2,
                weight:1,
                type:{
                    blunt:true
                }
            },
            value:2
        },
        mace:{
            weapon:true,
            name:"mace",
            damage:5,
            stunTime:3,
            weight:1,
            type:{
                blunt:true
            },
            jab:{
                damage:2,
                stunTime:2,
                weight:1,
                type:{
                    blunt:true
                }
            },
            value:4
        },
        hammer:{
            weapon:true,
            name:"hammer",
            damage:8,
            stunTime:5,
            weight:2,
            type:{
                blunt:true
            },
            jab:{
                damage:2,
                stunTime:4,
                weight:1,
                type:{
                    blunt:true
                }
            },
            value:5
        },
        maul:{
            weapon:true,
            name:"maul",
            damage:12,
            stunTime:7,
            weight:3,
            type:{
                blunt:true
            },
            jab:{
                damage:2,
                stunTime:5,
                weight:2,
                type:{
                    blunt:true
                }
            },
            value:7
        },
        rapier:{
            weapon:true,
            name:"rapier",
            damage:2,
            stunTime:2,
            weight:1,
            type:{
                sword:true,
            },
            jab:{
                damage:8,
                stunTime:2,
                weight:1,
                type:{
                    sword:true,
                },
            },
            value:7
        },
        shortsword:{
            weapon:true,
            name:"shortsword",
            damage:4,
            stunTime:2,
            weight:1,
            type:{
                sword:true,
                edged:true
            },
            value:4
        },
        longsword:{
            weapon:true,
            name:"longsword",
            damage:8,
            stunTime:3,
            weight:2,
            type:{
                sword:true,
                edged:true
            },
            value:7
        },
        greatsword:{
            weapon:true,
            name:"greatsword",
            damage:12,
            stunTime:4,
            weight:3,
            type:{
                sword:true,
                edged:true
            },
            value:10
        },
        handaxe:{
            weapon:true,
            name:"handaxe",
            damage:1,
            stunTime:2,
            weight:1,
            type:{
                edged:true
            },
            swing:{
                damage:6,
                stunTime:4,
                weight:1,
                type:{
                    edged:true
                }
            },
            value:4
        },
        greataxe:{
            weapon:true,
            name:"greataxe",
            damage:2,
            stunTime:3,
            weight:2,
            type:{
                edged:true
            },
            swing:{
                damage:15,
                stunTime:6,
                weight:3,
                type:{
                    edged:true
                }
            },
            value:9
        },
        halberd:{
            weapon:true,
            name:"halberd",
            damage:10,
            stunTime:3,
            weight:2,
            type:{
                edged:true,
                long:true
            },
            swing:{
                damage:15,
                stunTime:4,
                weight:4,
                type:{
                    edged:true,
                    long:true
                }
            },
            value:8
        },
    },
    fuel:{
        oilFlask:{
            usable:true,
            name: "oil flask",
            fuel:true,
            light:2,
            uses:3,
            value:5
        }
    },
    treasure:{
        thimble:{
            name:"thimble",
            value:1
        },
        ring:{
            name:"ring",
            value:2
        },
        cup:{
            name:"cup",
            value:3
        },
        plate:{
            name:"plate",
            value:5
        },
        vase:{
            name:"vase",
            value:7
        },
        pendant:{
            name:"pendant",
            value:3
        },
        statuette:{
            name:"statuette",
            value:8
        },
        crown:{
            name:"crown",
            value:15
        },
        tiara:{
            name:"tiara",
            value:12
        },
        coinPouch:{
            name:"coin pouch",
            value:10
        }
    }
}