let monsterVars = {
    goblin:{
        name:"goblin",
        symbol:"G",
        behavior:"chase",
        behaviorInfo:{
            focus:20,
            enrage:10,
            daze:40,
            beat:10
        },
        hitDice:1,
        damage:4,
        inventorySlots: 2,
        inventory:[
            {
                item: itemVars.food.morsel,
                chance:5
            },
            {
                item: itemVars.potions.unlabeled,
                chance: 1
            },
        ],
        loot:{
            weapon:{
                chance:5,
                tier:1
            },
            treasure:{
                chance:5,
                tier:0
            },
            gold:{
                chance:20,
                amount:3
            }
        },
        color:'darkGreen'
    },
    goblinBoss:{
        name:"goblin boss",
        symbol:"Gb",
        behavior:"chase",
        behaviorInfo:{
            focus:25,
            enrage:20,
            daze:30,
            beat:20
        },
        hitDice:3,
        damage:6,
        inventorySlots: 3,
        inventory:[
            {
                item: itemVars.food.morsel,
                chance:10
            },
            {
                item: itemVars.potions.unlabeled,
                chance: 5
            },
        ],
        loot:{
            weapon:{
                chance:10,
                tier:2
            },
            treasure:{
                chance:30,
                tier:4
            },
            gold:{
                chance:50,
                amount:20
            },
            potion:{
                chance:20,
                tier:1
            }
        },
        color:'darkGreen'
    },
    ogre:{
        name:"ogre",
        symbol:"Og",
        behavior:"chase",
        behaviorInfo:{
            focus:10,
            enrage:75,
            slow:40,
            beat:30,
            sturdy:30
        },
        hitDice:5,
        damage:8,
        inventorySlots: 10,
        inventory:[
            {
                item: itemVars.food.morsel,
                chance:20
            },
            {
                item: itemVars.food.morsel,
                chance:20
            }
        ],
        loot:{
            weapon:{
                chance:20,
                tier:1
            },
            treasure:{
                chance:30,
                tier:1
            },
            gold:{
                chance:45,
                amount:7
            },
            potion:{
                chance: 10,
                tier: 2
            }
        },
        color:'green'
    },
    rat:{
        name:"rat",
        symbol:"Ra",
        behavior:"chase",
        behaviorInfo:{
            focus:15,
        },
        hitDice:0,
        damage:1,
        inventorySlots: 0,
        tiny:true,
        color:'gray'
    },
    direRat:{
        name:"dire rat",
        symbol:"Dr",
        behavior:"chase",
        behaviorInfo:{
            focus:20,
            enrage:30,
            daze:20
        },
        hitDice:1,
        damage:4,
        inventorySlots: 1,
        inventory:[
            {
                item: itemVars.drops.direRatPelt,
                chance:100
            }
        ],
        color:'gray'
    },
    kingRat:{
        name:"king rat",
        symbol:"Kr",
        behavior:"chase",
        behaviorInfo:{
            focus:25,
            enrage:30
        },
        hitDice:4,
        damage:6,
        inventorySlots: 1,
        inventory:[{
            item: itemVars.drops.kingRatSkull,
            chance:100
        }],
        color:'darkRed'
    },
    wolf:{
        name:"wolf",
        symbol:"Wo",
        behavior:"chase",
        behaviorInfo:{
            focus:25,
            enrage:40,
            daze:15
        },
        hitDice:1,
        damage:5,
        inventorySlots: 1,
        inventory:[
            {
                item: itemVars.drops.wolfPelt,
                chance:100
            }
        ],
        color:'gray'
    },
    direWolf:{
        name:"dire wolf",
        symbol:"Dw",
        behavior:"chase",
        behaviorInfo:{
            focus:25,
            enrage:75,
            daze:10
        },
        hitDice:3,
        damage:8,
        inventorySlots: 1,
        inventory:[
            {
                item: itemVars.drops.direWolfPelt,
                chance:100
            }
        ],
        color:'gray'
    },
    zombie:{
        name:"zombie",
        symbol:"Zo",
        behavior:"chaseBinary",
        vulnerabilities:['silver'],
        behaviorInfo:{
            slow:35
        },
        hitDice:3,
        damage:4,
        inventorySlots: 1,
        inventory:[
        ],
        loot:{
            weapon:{
                chance:1,
                tier:1
            },
            treasure:{
                chance:5,
                tier:1
            },
            gold:{
                chance:5,
                amount:10
            },
            potion:{
                chance:2,
                tier:1
            }
        },
        reconstitute:2,
        reconstituteBehavior:'chaseBinary',
        reconstituteChance:50,
        color:'darkGreen'
    },
    skeletonPile:{
        name:"skeleton",
        symbol:"Sk",
        behavior:"chaseBinary",
        vulnerabilities:['silver'],
        behaviorInfo:{
            slow:20
        },
        threshold:16,
        hitDice:0,
        mortal:23,
        damage:4,
        reconstitute:2,
        reconstituteBehavior:'chaseBinary',
        reconstituteChance:50,
        inventorySlots: 2,
        inventory:[
            {
                item: itemVars.drops.sigiledSkull,
                chance:20
            },
            {
                item: itemVars.drops.sigiledBone,
                chance:100
            }
        ],
        loot:{
            weapon:{
                chance:15,
                tier:0,
                allowedMaterials: ['bone','sigiledBone', 'obsidian','glass','crystal','lead','copper','bronze','iron']
            },
            treasure:{
                chance:15,
                tier:1
            },
            gold:{
                chance:10,
                amount:5
            },
            potion:{
                chance:1,
                tier:1
            }
        },
        blood:0,
        color:'bone'
    },
    skeleton:{
        name:"skeleton",
        symbol:"Sk",
        behavior:"chaseBinary",
        vulnerabilities:['silver'],
        behaviorInfo:{
            slow:20
        },
        threshold:16,
        hitDice:0,
        mortal:14,
        damage:4,
        reconstitute:2,
        reconstituteBehavior:'chaseBinary',
        reconstituteChance:50,
        inventorySlots: 1,
        inventory:[
            {
                item: itemVars.drops.sigiledSkull,
                chance:20
            },
            {
                item: itemVars.drops.sigiledBone,
                chance:100
            }
        ],
        loot:{
            weapon:{
                chance:15,
                tier:0,
                allowedMaterials: ['bone','sigiledBone', 'obsidian','glass','crystal','lead','copper','bronze','iron']
            },
            treasure:{
                chance:15,
                tier:1
            },
            gold:{
                chance:10,
                amount:5
            },
            potion:{
                chance:1,
                tier:1
            }
        },
        blood:0,
        color:'bone'
    },
    ghoul:{
        name:"ghoul",
        symbol:"Gh",
        behavior:"chaseBinary",
        vulnerabilities:['silver'],
        behaviorInfo:{
            slow:10
        },
        hitDice:3,
        damage:6,
        inventorySlots: 2,
        inventory:[
        ],
        loot:{
            weapon:{
                chance:5,
                tier:2
            },
            treasure:{
                chance:15,
                tier:2
            },
            gold:{
                chance:10,
                amount:10
            },
            potion:{
                chance:15,
                tier:1
            }
        },
        reconstitute:2,
        reconstituteBehavior:'chaseBinary',
        reconstituteChance:25,
        color:'white'
    },
    corrosiveOoze:{
        name:"corrosive ooze",
        symbol:"Oo",
        behavior:"chaseBinary",
        hitDice:1,
        damage:1,
        corrosive:1,
        blood:1,
        inventorySlots:3,
        behaviorInfo:{
            slow:35
        },
        reconstitute:1,
        reconstituteBehavior:'chaseBinary',
        reconstituteChance:20,
        color:"green",
        bloodColor:{r:29,g:189,b:66}
    },
    absorbentOoze:{
        name:"absorbent ooze",
        symbol:"Oo",
        behavior:"chaseBinary",
        hitDice:1,
        damage:1,
        blood:1,
        grabby:1,
        inventorySlots:3,
        reconstitute:1,
        reconstituteBehavior:'chaseBinary',
        reconstituteChance:20,
        behaviorInfo:{
            slow:35
        },
        color:"orange",
        bloodColor:{r:211,g:147,b:28}
    },
    //should spawn ....
    elderGoo:{
        name:"elder goo",
        symbol:"Oo",
        behavior:"chaseBinary",
        hitDice:6,
        damage:3,
        blood:2,
        grabby:1,
        corrosive:1,
        inventorySlots:5,
        reconstitute:3,
        reconstituteBehavior:'chaseBinary',
        reconstituteChance:100,
        behaviorInfo:{
            slow:35
        },
        spawnEntities:{ 
            minCapacity:3,
            maxCapacity:8,
            minSpawn:1,
            maxSpawn:2,
            entities:[
                "absorbentOoze",
                "corrosiveOoze"
            ],
            randomEntities:true,
            spawnChance: 1,
            disturbChance:100,
        },
        color:"brightPurple",
        bloodColor:{r:173,g:26,b:202}
    },
    dummy:{
        name:"dummy",
        symbol:"Du",
        behavior:"",
        hitDice:100,
        damage:8,
        inventorySlots: 0,
    }
}