let skillVars = {
    hp:[
        {
            type:"raiseBarMax",
            bar:"hp",
            amount:2,
        }
    ],
    stamina:[
        {
            type:"raiseBarMax",
            bar:"stamina",
            amount:2
        },
    ],
    luck:[
        {
            type:"raiseBarMax",
            bar:"luck",
            amount:2
        }
    ],
    hunger:[
        {
            type:"raiseBarMax",
            bar:"hunger",
            amount:2
        }
    ],
    bulk:[
        {
            type:"raiseBarMax",
            bar:"bulk capacity",
            amount:2
        }
    ],
    swords:[
        {
            type:"advantage",
            attackType:"sword"
        }
    ],
    axes:[
        {
            type:"advantage",
            attackType:"axe"
        }
    ],
    blunt:[
        {
            type:"advantage",
            attackType:"blunt" 
        }
    ],
    long:[
        {
            type:"advantage",
            attackType:"long" 
        }
    ],
    edged:[
        {
            type:"advantage",
            attackType:"edged" 
        }
    ],
    improvised:[
        {
            type:"advantage",
            attackType:"improvised" 
        }
    ],
    simple:[
        {
            type:"advantage",
            attackType:"simple" 
        }
    ],
    unarmed:[
        {
            type:"advantage",
            attackType:"unarmed" 
        },
        {
            type:"critChance",
            attackType:"unarmed",
            chance:0.2 
        }
    ],
    swing:[
        {
            type:"critChance",
            attackType:"swing",
            chance: 0.2
        }
    ],
    jab:[
        {
            type:"critChance",
            attackType:"jab",
            chance: 0.2
        }
    ],
    draw:[
        {
            type:"critChance",
            attackType:"draw",
            chance: 0.2
        }
    ],
    strafe:[
        {
            type:"critChance",
            attackType:"strafe",
            chance: 0.2
        }
    ],
    counterattack:[
        {
            type:"critChance",
            attackType:"counterattack",
            chance: 0.35
        }
    ],
    sell:[
        {
            type:"misc",
            category:"sell",
            name:"trinket peddler",
            key:"trinketPeddler",
            description:"Sell all treasure for +1 gold."
        },
        {
            type:"misc",
            category:"sell",
            name:"appraiser",
            key:"appraiser",
            description:"Sell all treasure for +20% gold."
        },
    ],
    buy:[

    ]
}