let skillVars = {
    hp:[
        {
            type:"raiseBarMax",
            bar:"hp",
            amount:2
        }
    ],
    stamina:[
        {
            type:"raiseBarMax",
            bar:"stamina",
            amount:2
        }
    ],
    luck:[
        {
            type:"raiseBarMax",
            bar:"luck",
            amount:2
        }
    ],
    hunger:[
        {
            type:"raiseBarMax",
            bar:"hunger",
            amount:2
        }
    ],
    swords:[
        {
            type:"weaponAdv",
            weaponType:"sword"
        }
    ],
    axes:[
        {
            type:"weaponAdv",
            weaponType:"axe"
        }
    ],
    blunt:[
        {
            type:"weaponAdv",
            weaponType:"blunt" 
        }
    ],
    long:[
        {
            type:"weaponAdv",
            weaponType:"long" 
        }
    ],
    edged:[
        {
            type:"weaponAdv",
            weaponType:"edged" 
        }
    ],
    improvised:[
        {
            type:"weaponAdv",
            weaponType:"improvised" 
        }
    ],
    unarmed:[
        {
            type:"weaponAdv",
            weaponType:"unarmed" 
        }
    ]
}