let tipVars = [
    "Ogres are dangerous, but have limited interest in you unless you bother them. If you can't fight them, leave them alone!",
    "Remember you can move diagonally! This opens up many useful maneuvers in combat.",
    "Luck does not regenerate passivley. Use it sparingly!",
    "Weapon breaking is completely random - you can use luck to make your weapons last longer!",
    "Stunned enemies appear in lower case, and recieve guaranteed critical hits. Press the advantage!",
    "Scroll over an object with your mouse to see what it is.",
    "Scroll over a bolded keyword to see what it means.",
    "Objects like shrubs, tables, and bedrolls may contain treasure - push against them or destroy them to search them!",
    "Paper burns bright, but not very long. Burn it if you need a quick burst of light.",
    "The contents of unlabeled potions are undetermined until the moment you drink them. Use luck to make better use of them.",
    "Some lootable objects like shrubs and rat stashes have a chance to restock as days pass.",
    "Most oozes have a low sight radius. Keep your distance if you don't want to fight them.",
    "Corrosive(green) and absorbent(orange) oozes track your weapon instead of you. Put it away and they'll leave you alone!",
    "Black oozes follow the heat of your lantern. The lower your light, the lower their detection range.",
    "Smarter monsters will remember where they last saw you. Run around a corner and then hide to escape them.",
    "Heavier weapons make more sound. Use lighter weapons around sleeping enemies to remain undetected.",
    "Your proficiency with a weapon is represented by a number of '+'s next to that weapon's name. Scroll over the '+'s to learn more.",
    "Skills that are used more are more likely to be recieved as levelup rewards. This includes taking damage and using luck!",
    "Guaranteed crits are applied separately from crits achieved via crit chance. They scale multiplicitively!",
    "A dubious food item's flavor text can give you a hint to its likelihood of being rotten.",
    "Be very wary of corridors that are only one tile wide. Being cornered there is sure death.",
    "Watch your bulk - carrying more than your max can cause you to lose turns at random intervals.",
    "While in a dungeon, equipped items don't count towards your bulk. Equip a hefty piece of treasure to make a hasty escape.",
    "Weapons score a guaranteed crit when they break while attacking an enemy.",
    "When resting, benefits trickle down from Hunger to Fatigue to Health - Resting with high hunger will help deplete Fatigue, and resting with low Fatigue will help regain Health.",
    "Traveling with a heavy load causes high amounts of Fatigue to accumulate. Pack lightly when traveling far.",
    "Fatigue can't kill you, but it can lower your health if it gets high enough."
]